kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: platform
networking:
  disableDefaultCNI: true
  # Disable kube-proxy - Cilium will handle service load balancing
  kubeProxyMode: none
nodes:
- role: control-plane
  image: kindest/node:v1.33.0
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 8080
    hostPort: 8080
    protocol: TCP
  # Label for BGP speaker
  labels:
    bgp: enabled
- role: worker
  image: kindest/node:v1.33.0
  labels:
    bgp: enabled
