kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: platform
networking:
  disableDefaultCNI: true
  # Disable kube-proxy - Cilium will handle service load balancing
  kubeProxyMode: none
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  dns:
    type: None
nodes:
- role: control-plane
  image: kindest/node:v1.34.0
  # Label for BGP speaker
  labels:
    bgp: enabled
    ingress-ready: "true"
- role: worker
  image: kindest/node:v1.34.0
  labels:
    bgp: enabled
    ingress-ready: "true"
