apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd-cm.yaml
  - argocd-rbac-cm.yaml
  - argocd-cmd-params-cm.yaml
  - argocd-server-patch.yaml
  # Uncomment after creating the sealed secret
  # - argocd-github-oauth-sealed-secret.yaml

sortOptions:
  order: fifo
