apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - _namespace.yaml
  - _argocd-config.yaml
  - _infra-apps.yaml
  - _platform-apps.yaml

sortOptions:
  order: fifo
