apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - _namespace.yaml
  - _coredns.yaml
  - _cilium.yaml
  - _argocd-config.yaml
  - _infra-apps.yaml
  - _platform-apps.yaml
  - argocd-cm.yaml
  - argocd-rbac-cm.yaml
  # Uncomment after creating the sealed secret
  # - argocd-github-oauth-sealed-secret.yaml

sortOptions:
  order: fifo
