apiVersion: v2
name: my-app
description: Example application for Kubernetes Platform Stack
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - helm
  - example
maintainers:
  - name: Kevin Vu
    email: vietcgi@gmail.com
