apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- ingress.yaml

commonLabels:
  app: my-app
  managed-by: kustomize

commonAnnotations:
  description: "My application"

images:
- name: my-app
  newName: ghcr.io/vietcgi/kubernetes-platform-stack
  newTag: latest

replicas:
- name: my-app
  count: 2
