apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-dev

bases:
- ../../base

replicas:
- name: my-app
  count: 1

images:
- name: my-app
  newTag: dev

commonLabels:
  environment: development

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: my-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 64Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 256Mi
